# Generated by Django 6.0.5 on 2026-06-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='place',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
